# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Keep Workflows Alive

on:  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  schedule:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
  - cron:  '0 0 1 * *' # monthly
  workflow_dispatch:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch


defaults:
  run:
    shell: bash


jobs:
  keep-workflows-alive:
    runs-on: ubuntu-latest  # https://github.com/actions/runner-images#available-images

    steps:
    - name: Keep Workflows alive
      run: |
        set -euxo pipefail

        workflow_api_url=https://x-access-token:${{ secrets.GITHUB_TOKEN }}@api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows

        workflows=$(curl -sSf -H "Accept: application/vnd.github.v3+json" $workflow_api_url | jq '.workflows[]| (.id|tostring) + "_" + .name' -r)
        for workflow in $workflows; do
          workflow_id=$(echo "$workflow" | cut -d: -f2-)
          workflow_name=$(echo "$workflow" | cut -d: -f1)
          echo "Enabling [$workflow_name] with id [$workflow_id]..."
          curl -I -X PUT -H "Accept: application/vnd.github.v3+json" $workflow_api_url/$workflow_id/enable
        done
